version: '3.8'

services:
  frontend-service:
    container_name: frontend-service
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "4200:4200"
    restart: always
    volumes:
      - ./frontend-service:/app
    networks:
      - mypfe-network

  backend-service:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - CONN_STR=mongodb://user:pass@mongodb:27017/mydatabase?authSource=admin
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
        - ./backend-service:/app
    networks:
      - mypfe-network

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    networks:
      - mypfe-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./data
        target: /data/db

networks:
  mypfe-network:
    driver: bridge

