version: '3.8' # specify docker-compose version

services:
  backend-service:
    container_name: backend-service
    build:
      context: "."
      dockerfile: "./Dockerfile"
    #depends_on:
    #s - mongo-backend
    ports:
      - 3000:3000
    volumes:
      - ./backend-service:/app
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo-backend:27017/

  mongo-backend:
    container_name: mongo-backend
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./init-mongo.js:/app/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./mongo-volume:/app/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 7202:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo-backend:27017/
